apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: ratify-gatekeeper-provider
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v2/verify
  timeout: {{ required "You must provide .Values.provider.timeout.validationTimeoutSeconds" .Values.provider.timeout.validationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" . | nindent 2}}
---
{{- if not .Values.provider.disableMutation }}
apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: ratify-gatekeeper-mutation-provider
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v2/mutate
  timeout: {{ required "You must provide .Values.provider.timeout.mutationTimeoutSeconds" .Values.provider.timeout.mutationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" . | nindent 2}}
{{- end }}