apiVersion: v1
kind: Secret
metadata:
  name: ratify-notation-certs
type: Opaque
stringData:
{{- range $index, $cert := .Values.notation.certs }}
  ratify{{ $index }}.crt: |
{{ $cert | indent 4 }}
{{- end }}