# Always validate the PR title, and ignore the commits
titleOnly: true
types:
  - build
  - chore
  - ci
  - docs
  - feat
  - fix
  - perf
  - refactor
  - release
  - revert
  - security
  - style
  - test
