# Check the documentation at https://goreleaser.com for more options
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: ratify-gatekeeper-provider
    dir: cmd/ratify-gatekeeper-provider
    binary: ratify-gatekeeper-provider
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:

release:
  prerelease: auto
  draft: true
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
