# Default values for ratify.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

notation:
  scope: []
  trustedIdentities: []
  certs: []
  
stores:
  - scope: ""
    username: ""
    password: ""

provider:
  tls:
    crt: "" # crt used by ratify (httpserver), please provide your own crt
    key: "" # key used by ratify (httpserver), please provide your own key
    caCert: "" # CA crt used by ratify (httpserver), please provide your own CA crt
    cabundle: "" # base64 encoded CA bundle used for the 'caBundle' property for the ratify provider within gatekeeper
    disableCertRotation: false
  disableMutation: false
  timeout:
    # timeout values must match gatekeeper webhook timeouts
    validationTimeoutSeconds: 5
    mutationTimeoutSeconds: 2

gatekeeper:
  namespace: "gatekeeper-system"

serviceAccount:
  create: true
  name: ratify-gatekeeper-provider-admin
  # annotations to add to the service account
  annotations: {}
