image:
  repository: "ghcr.io/notaryproject/ratify-gatekeeper-provider"
  pullPolicy: IfNotPresent
  tag: "dev"

replicaCount: 1

executor:
  scopes: []
notation:
  scopes: []
  trustedIdentities: []
  certs:
    - provider: "inline"
      cert: "" # PEM encoded certificate, e.g. "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
  # - provider: "azurekeyvault" # use "azurekeyvault" to use Azure Key Vault
  #   vaultURL: "" # e.g. "https://my-key-vault.vault.azure.net/"
  #   clientID: "" # optional
  #   tenantID: "" # optional
  #   certificates:
  #     - name: "" # name of the certificate in Azure Key Vault
  #       version: "" # optional, if not provided, the latest version will be used
stores:
  - scopes: []
    credential:
      provider: "static"
      username: ""
      password: ""
    # provider: "azure" # use "azure" to use Azure Workload Identity
    # clientID: "" # optional
    # tenantID: "" # optional
provider:
  tls:
    crt: "" # crt used by ratify (httpserver), please provide your own crt
    key: "" # key used by ratify (httpserver), please provide your own key
    caCert: "" # CA crt used by ratify (httpserver), please provide your own CA crt
    disableCertRotation: false
  disableMutation: false
  disableCRDManager: false
  timeout:
    # timeout values must match gatekeeper webhook timeouts
    validationTimeoutSeconds: 5
    mutationTimeoutSeconds: 2

gatekeeper:
  namespace: "gatekeeper-system"

serviceAccount:
  create: true
  name: ratify-gatekeeper-provider-admin
  # annotations to add to the service account
  annotations:
    {}
    # add azure.workload.identity/client-id if using Azure Workload Identity
