---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  - namespacedpolicies
  - namespacedstores
  - namespacedverifiers
  - policies
  - stores
  - verifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/finalizers
  - namespacedpolicies/finalizers
  - namespacedstores/finalizers
  - namespacedverifiers/finalizers
  - policies/finalizers
  - stores/finalizers
  - verifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  - namespacedpolicies/status
  - namespacedstores/status
  - namespacedverifiers/status
  - policies/status
  - stores/status
  - verifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.dev
  resources:
  - executors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.dev
  resources:
  - executors/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.dev
  resources:
  - executors/status
  verbs:
  - get
  - patch
  - update
