apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: org.sigstore.cosign.v1
  parameters:
    key: /usr/local/ratify-certs/cosign/cosign.pub