apiVersion: v1
kind: ConfigMap
metadata:
  name: ratify-configmap
data:
  config.json: |
    {
      "verifiers": [
          {
              "name": "notation-1",
              "type": "notation",
              "parameters": {
                  "trustPolicyDocument": {
                      "Version": "1.0",
                      "trustPolicies": [
                          {
                              "name": "default",
                              "registryScopes": [
                                  "*"
                              ],
                              "signatureVerification": {
                                  "level": "strict"
                              },
                              "trustStores": [
                                  "ca:ratify4"
                              ],
                              "trustedIdentities": [
                                  "*"
                              ]
                          }
                      ]
                  },
                  "trustStorePath": "/usr/local/.config/notation"
              }
          }
      ],
      "stores": {
          "libinbinacr.azurecr.io": {
              "type": "registry-store",
              "parameters": {
                  "credential": {
                      "username": "",
                      "password": ""
                  }
              }
          }
      },
      "policyEnforcer": {
          "type": "threshold-policy",
          "parameters": {
              "policy": {
                  "rules": [
                      {
                          "verifierName": "notation-1"
                      }
                  ]
              }
          }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notation-configmap
data:
  trustpolicy.json: |
{{ .Values.notation.trustpolicy | indent 4 }}