{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ratify-manager-cluster-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - keymanagementproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterstores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterverifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterverifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterverifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clustercertificatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clustercertificatestores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clustercertificatestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - clusterpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - externaldata.gatekeeper.sh
  resources:
  - providers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
# Secrets access is used for k8s auth provider to access secrets across namespaces.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
{{- end }}
