apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-rego-policy
data:
  policy.rego: |
    package ratify.policy
    default valid := false
    valid {
      not failed_verify(input)
    }
    failed_verify(reports) {
        [path, value] := walk(reports)
        value == false
        path[count(path) - 1] == "isSuccess"
    }