{{- if and .Values.rbac.create .Values.featureFlags.RATIFY_CERT_ROTATION }}
# secret-role is used by cert-controller to listing/updating TLS related secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secret-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - update
  - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: secret-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "ratify.serviceAccountName" . }} 
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: Role
  name: secret-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
