apiVersion: v1
kind: Secret
metadata:
  name: ratify-notation-certs
type: Opaque
stringData:
{{- range $filename, $content := .Values.notation.certs }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}