apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-notary-certificate
data:
  ratify-test.crt: {{ .Values.ratifyTestCert | b64enc | quote }}

---

{{- if .Values.cosign.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-cosign-certificate
data:
  cosign.pub: {{ .Values.cosign.key | b64enc | quote }}

{{- end }}
 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  annotations:
  helm.sh/hook: pre-install,pre-upgrade
  helm.sh/hook-weight: "1"
  helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
data:
  {{- if and .Values.provider.tls.crt .Values.provider.tls.key .Values.provider.tls.cabundle }}
  tls.crt: {{ .Values.provider.tls.crt | b64enc | quote }}  
  tls.key: {{ .Values.provider.tls.key | b64enc | quote }}
  cabundle: {{ .Values.provider.tls.cabundle | quote }}
  {{- else }}
  {{- $ca := genCA "/O=Ratify/CN=Ratify Root CA" 365 -}}
  {{- $cert := genSignedCert "/CN=ratify.gatekeeper-system" nil (list "ratify.gatekeeper-system") 365 $ca -}}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  cabundle: {{ $ca.Cert | b64enc | replace "\n" "" }}
  {{- end }}
