apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratify.fullname" . }}
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6001
      targetPort: 6001
  selector:
    {{- include "ratify.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: ratify
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: ratify
  name: ratify-webhook-service
  namespace: gatekeeper-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: ratify
