apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedPolicy
metadata:
  name: "ratify-policy"
spec:
  type: "config-policy"
  parameters:
    artifactVerificationPolicies:
      default: "all"
