apiVersion: config.ratify.dev/v2alpha1
kind: Executor
metadata:
  labels:
    app.kubernetes.io/name: testcrd
    app.kubernetes.io/managed-by: kustomize
  name: executor-sample
spec:
  # TODO(user): Add fields here
