# This rule is not used by the project testcrd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to config.ratify.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testcrd
    app.kubernetes.io/managed-by: kustomize
  name: executor-viewer-role
rules:
- apiGroups:
  - config.ratify.dev
  resources:
  - executors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.ratify.dev
  resources:
  - executors/status
  verbs:
  - get
