name: 'Restore Trivy cache directory'
on:
  workflow_call:

permissions: read-all

jobs:
  restore_trivy_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Restore trivy cache directory
        uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ${{ github.workspace }}/.cache/trivy
          key: cache-trivy-${{ steps.date.outputs.date }}
      - name: Set up trivy cache directory
        run: |
          mkdir -p ~/.cache/trivy
          cp -r ${{ github.workspace }}/.cache/trivy/db ~/.cache/trivy